name: pfe_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  geolocator: ^8.2.0
  http: ^0.13.4
  permission_handler: ^9.2.0
  rflutter_alert: ^2.0.4
  carousel_slider: ^4.1.1
  google_maps_flutter: ^2.1.4
  flutter_polyline_points: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - images/