import 'package:flutter/material.dart';

const kText = Text(
  //'   Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed feugiat lacinia arcu, condimentum dignissim magna porttitor eu. Quisque id vestibulum quam. Morbi justo sapien, varius ut felis eu, scelerisque mollis sem. Integer tristique enim dui, at lobortis lorem tristique sed. Nunc et iaculis orci. Duis vel commodo augue. Praesent dignissim quis tortor at ultricies. Donec ultricies, arcu tempus molestie finibus, enim ante dignissim eros, eget interdum elit nunc et elit. Ut lobortis turpis vel elit commodo, quis sodales enim lobortis. Sed lacinia, dui quis placerat condimentum, nisl lectus rhoncus metus, vitae congue magna turpis vel nunc. Aliquam finibus leo eu tortor consequat vestibulum. Aenean at finibus lorem, nec finibus dui. Ut non fermentum erat. Curabitur imperdiet gravida semper. Mauris id orci sollicitudin, mollis justo non, viverra turpis. Nam efficitur sem in leo dapibus, et pharetra est volutpat.\n  Vestibulum ornare vulputate pretium. Duis viverra, orci ut mattis bibendum, ligula sem gravida ligula, eu ullamcorper tellus libero at nulla. Mauris sagittis aliquam lacus, id tincidunt mi cursus eget. Donec blandit pulvinar diam, nec fermentum nisi bibendum ac. Sed dui quam, sodales et odio ac, gravida efficitur lacus. Etiam pretium arcu nec rhoncus porta. Vestibulum at luctus velit. Aenean sed ante dapibus nibh pretium gravida. Sed sit amet nulla aliquet, convallis magna vel, cursus ex. Suspendisse risus arcu, ultricies in pretium id, congue eu libero. Cras nisl nunc, rutrum et tincidunt non, auctor vel erat. Nullam efficitur, nulla vel finibus ultricies, velit metus facilisis ligula, pretium sagittis enim turpis at odio. Donec venenatis gravida velit, sit amet vehicula ligula dapibus a. Phasellus tincidunt cursus lacus eget sollicitudin. Ut mauris felis, viverra ut massa vel, consequat laoreet nisi. \n Curabitur blandit finibus facilisis. Integer rutrum, nunc fermentum accumsan aliquet, turpis erat mollis ligula, sed commodo urna nunc quis elit. Phasellus condimentum erat tortor, vitae cursus orci facilisis in. Nam sagittis velit venenatis, interdum ligula quis, viverra nibh. Mauris in volutpat tellus, eget posuere arcu. Aenean consequat lobortis augue, a vestibulum eros pulvinar a. Nunc diam enim, tempor id pharetra nec, laoreet at lectus. Nullam congue diam risus. Nunc odio orci, venenatis molestie efficitur in, pellentesque et erat. Morbi scelerisque felis at elit feugiat, quis dignissim nisl faucibus. Morbi a feugiat ligula.',
  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).\n Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.",
  style: TextStyle(
    color: Colors.black,
    fontSize: 15.0,
  ),
  textAlign: TextAlign.justify,
);
const kColorSelected = Color(0xFF5470FF);
const kTextColorSelected = Colors.white;
const kTextColorNotSelected = Colors.black;
const kColorNotSelected = Color(0xFFD7CCC8);
const kURl = 'https://www.pfeweb.ml/REST';
const kURlForImage = 'https://www.pfeweb.ml';

const String apiKeyWeather = 'a1173da81b738a5fdc4ad146f555d9ab&units=metric';